apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mvdn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-mvdn@sha256:f69118c1d5fbbf068b8bf7c2c836a52181f798b0c17b3eafc44f0446109c0026
        name: my-nodejs
        resources: {}
status: {}
